project_id = "roodcmebqkwmoxrfjdzq"

[functions.cancel-subscription]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-miro-board]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.generate-personal-flashcards]
verify_jwt = true

[functions.generate-personal-notes]
verify_jwt = true

[functions.generate-personal-quiz]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.learnspace-chat]
verify_jwt = true

[functions.phoenix-realtime-token]
verify_jwt = true

[functions.resume-subscription]
verify_jwt = true

[functions.send-career-application]
verify_jwt = false

[functions.aurora-application-builder]
verify_jwt = true

[functions.aurora-role-search]
verify_jwt = true

[functions.aurora-interview-questions]
verify_jwt = true

[functions.send-refund-request]
verify_jwt = false

[functions.teacher-assistant]
verify_jwt = true

[functions.nexus-curriculum-generator]
verify_jwt = true

[functions.nexus-assessment-generator]
verify_jwt = true

[functions.nexus-lesson-generator]
verify_jwt = true

[functions.grade-assessment]
verify_jwt = false

[functions.marketing-admin]
verify_jwt = true

[functions.smart-assistant]
verify_jwt = true

[functions.notify-educator-message]
verify_jwt = true
